# Generated by Django 2.2.19 on 2021-03-17 19:12

import apps.registro.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postulante',
            name='certificado',
            field=models.FileField(default=1, upload_to=apps.registro.models.upload_location, verbose_name='Certificado de Estudios'),
            preserve_default=False,
        ),
    ]
