# Generated by Django 2.2.19 on 2021-03-17 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0002_postulante_certificado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postulante',
            name='ap_materno',
            field=models.CharField(max_length=100, verbose_name='Apellido Materno'),
        ),
        migrations.AlterField(
            model_name='postulante',
            name='carrera',
            field=models.IntegerField(choices=[('CC', 'Contrucción Civil'), ('C', 'Contabilidad'), ('EM', 'Explotación Minera')], verbose_name='Programa de Estudios al que postula'),
        ),
        migrations.AlterField(
            model_name='postulante',
            name='fecha_nac',
            field=models.DateField(verbose_name='Fecha de Nacimiento (dd/MM/AAAA'),
        ),
        migrations.AlterField(
            model_name='postulante',
            name='sexo',
            field=models.IntegerField(choices=[('M', 'Masculino'), ('F', 'Femenino')], verbose_name='Sexo'),
        ),
    ]
